Mention users in comments
mediacms-io/mediacms pull request #429
Opened 2022-03-15 09:43 UTC by MrPercheul

## Description
This change adds the react component "react-mentions" (https://github.com/signavio/react-mentions) in the comment section so that users can tag one another.

When typing '@' in a comment, a suggestion list will be rendered will all the users, and you can pick one to add him to the comment. The name will be highlighted following the color scheme (10% lighter/darker than #009933) and saved on the BD as "texttext **@[_IDUser_](_DisplayName_)** texttext"

Comments rendered under the media will watch for these markups and replace it with the appropriate anchor (<a href="/user/**IDUser**>**DisplayName**</a>)

2022-03-16 08:14 UTC, swiftugandan commented on files/methods.py
> +    # cleaned_comment = "</div>".join(cleaned_comment.split("_]"))
delete?

2022-03-23 18:46 UTC, mgogoulos requested changes
First of all sync with master to solve the conflict (after I merged your other PR!) 

Besides some minor issues added here (mostly typos), the biggest issue with it is that it adds a call to users API every time you visit a media page. This cannot be the behavior out of the box, so I suggest that you make it configurable, and that by default this feature is disabled. 

For example it can be a setting on cms/settings.py as MENTION_USERS_IN_COMMENTS that is False (and on local_settings.py you override with True). Then you may pass this variable on files/context_processors.py, and have the frontend read it as it does on  templates/config/  ...

2022-03-23 18:46 UTC, mgogoulos commented on files/methods.py
> +def notify_user_on_mention(friendly_token, user_mentionned, cleaned_comment):
s/user_mentionned/user_mentioned

2022-03-23 18:46 UTC, mgogoulos commented on files/methods.py
> +    """ Notify the user mentionned in the comment """
s/mentionned/mentioned

2022-03-23 18:46 UTC, mgogoulos commented on files/methods.py
> +    media = None
this line is not needed

2022-03-23 18:46 UTC, mgogoulos commented on files/methods.py
> +    """ Check the comment for any mentions, and notify each mentionned users"""
s/mentionned/mentioned

2022-04-05 08:14 UTC, MrPercheul commented
The changes are in and the Typos corrected, however I did not get a precommit black failed when running it on my side, anyway of checking which file is the cultprit?

2022-04-06 10:01 UTC, MrPercheul commented on files/methods.py
> +    """ Check the comment for any mentions, and notify each mentionned users"""
typo fixed

2022-04-06 10:01 UTC, MrPercheul commented on files/methods.py
> +    media = None
Typo fixed

2022-04-06 10:01 UTC, MrPercheul commented on files/methods.py
> +    """ Notify the user mentionned in the comment """
Typo fixed

2022-04-06 10:02 UTC, MrPercheul commented on files/methods.py
> +def notify_user_on_mention(friendly_token, user_mentionned, cleaned_comment):
Typo fixed

2022-04-13 10:49 UTC, MrPercheul commented
There is an issue with Pre-commit, the 'click' library used by black is causing trouble, it is fixed in this commit and I will also submit another PR just for the .pre-commit-config.yaml change

2022-05-03 18:29 UTC, mgogoulos commented on files/methods.py
> +    media = None
I am refering to the `media = None` here. 

media on this queryset will be None if it doesn't find one, that's why I commented that `media = None` is redundant!
```
media = models.Media.objects.filter(friendly_token=friendly_token).first()
```

2022-05-03 18:31 UTC, mgogoulos commented on files/methods.py
> +
can you bring the `from users.models import User` here, and not on the top level? Just in case no weird cyclic import error can  happen

2022-05-03 18:35 UTC, mgogoulos commented
looks good, I will give it another test and merge it once you make the following two changes:

1. handle last 2 small issues
2. add an entry on the documentation, on how this is used, and probably a screenshot too

Thanks!

2022-05-25 09:50 UTC, MrPercheul commented
Hi, the changes are in, and the entry in the user_docs.md too

2022-06-01 11:23 UTC, mgogoulos commented
merging this, very useful functionality, thanks for introducing!

2022-06-01 11:23 UTC, merged